service: pupsrb-imhealth-students

custom:
  config: ${file(../../environments/${opt:stage}.config.yml)}
  pythonRequirements:
    pythonBin: python
    slim: true

provider:
  name: aws
  runtime: python3.14
  architecture: x86_64
  region: ${self:custom.config.region}
  environment: ${self:custom.config.environment}
  layers: ${self:custom.config.layers}
  apiGateway: ${self:custom.config.apiGateway}
  iam:
    role: ${self:custom.config.lambdaRoleArn}

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.serverless/**"
    - "../../constants/**"
    - "../../utils/**"
    - "../../models/**"
    - "../../generic_dals/**"

functions:
  listPrograms:
    handler: list_programs.handler
    events:
      - http:
          path: /programs
          method: get
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true

  listStudents:
    handler: list_students.handler
    events:
      - http:
          path: /students
          method: get
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.authorizerId}
  getStudent:
    handler: get_student.handler
    events:
      - http:
          path: /students/{user_id}
          method: get
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.authorizerId}

  createPersonalDetails:
    handler: create_personal_details.handler
    events:
      - http:
          path: /students/personal-details
          method: post
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.studentAuthorizerId}

  getPersonalDetails:
    handler: get_personal_details.handler
    events:
      - http:
          path: /students/personal-details
          method: get
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.studentAuthorizerId}

  updatePersonalDetails:
    handler: update_personal_details.handler
    events:
      - http:
          path: /students/personal-details
          method: put
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.studentAuthorizerId}

  importStudentsCsv:
    handler: import_students_csv.handler
    events:
      - http:
          path: /students/import
          method: post
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.authorizerId}

  updateStudent:
    handler: update_student.handler
    events:
      - http:
          path: /students/{user_id}
          method: put
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.authorizerId}
