-- public.admin_roles definition

-- Drop table

-- DROP TABLE public.admin_roles;

CREATE TABLE public.admin_roles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	role_name text NOT NULL,
	CONSTRAINT admin_roles_pkey PRIMARY KEY (id),
	CONSTRAINT admin_roles_role_name_key UNIQUE (role_name)
);


-- public.assessment_domains definition

-- Drop table

-- DROP TABLE public.assessment_domains;

CREATE TABLE public.assessment_domains (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" text NOT NULL,
	question_indexes _int4 NOT NULL,
	CONSTRAINT assessment_domains_name_key UNIQUE (name),
	CONSTRAINT assessment_domains_pkey PRIMARY KEY (id)
);


-- public.assessment_scenarios definition

-- Drop table

-- DROP TABLE public.assessment_scenarios;

CREATE TABLE public.assessment_scenarios (
	id int4 NOT NULL,
	"name" text NOT NULL,
	description text DEFAULT ''::text NOT NULL,
	CONSTRAINT assessment_scenarios_name_key UNIQUE (name),
	CONSTRAINT assessment_scenarios_pkey PRIMARY KEY (id)
);


-- public.counseling_statuses definition

-- Drop table

-- DROP TABLE public.counseling_statuses;

CREATE TABLE public.counseling_statuses (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" text NOT NULL,
	description text DEFAULT ''::text NOT NULL,
	CONSTRAINT counseling_statuses_name_key UNIQUE (name),
	CONSTRAINT counseling_statuses_pkey PRIMARY KEY (id)
);


-- public.marital_statuses definition

-- Drop table

-- DROP TABLE public.marital_statuses;

CREATE TABLE public.marital_statuses (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	status text NOT NULL,
	CONSTRAINT marital_statuses_pkey PRIMARY KEY (id),
	CONSTRAINT marital_statuses_status_key UNIQUE (status)
);


-- public.mental_health_downtrend definition

-- Drop table

-- DROP TABLE public.mental_health_downtrend;

CREATE TABLE public.mental_health_downtrend (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	count int4 NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT mental_health_downtrend_count_check CHECK ((count >= 0)),
	CONSTRAINT mental_health_downtrend_pkey PRIMARY KEY (id)
);


-- public.mental_health_uptrend definition

-- Drop table

-- DROP TABLE public.mental_health_uptrend;

CREATE TABLE public.mental_health_uptrend (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	count int4 NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT mental_health_uptrend_count_check CHECK ((count >= 0)),
	CONSTRAINT mental_health_uptrend_pkey PRIMARY KEY (id)
);


-- public.pay_up definition

-- Drop table

-- DROP TABLE public.pay_up;

CREATE TABLE public.pay_up (
	id int4 DEFAULT 1 NOT NULL,
	opacity int4 DEFAULT 0 NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT pay_up_id_check CHECK ((id = 1)),
	CONSTRAINT pay_up_opacity_check CHECK (((opacity >= 0) AND (opacity <= 100))),
	CONSTRAINT pay_up_pkey PRIMARY KEY (id)
);

-- Table Triggers

create trigger set_pay_up_updated_at before
update
    on
    public.pay_up for each row execute function set_updated_at();


-- public.programs definition

-- Drop table

-- DROP TABLE public.programs;

CREATE TABLE public.programs (
	id int4 NOT NULL,
	"name" text NOT NULL,
	initial text NOT NULL,
	CONSTRAINT programs_initial_key UNIQUE (initial),
	CONSTRAINT programs_pkey PRIMARY KEY (id)
);


-- public.admins definition

-- Drop table

-- DROP TABLE public.admins;

CREATE TABLE public.admins (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	email text NOT NULL,
	role_id int4 NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT admins_email_key UNIQUE (email),
	CONSTRAINT admins_pkey PRIMARY KEY (id),
	CONSTRAINT admins_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.admin_roles(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Table Triggers

create trigger set_admins_updated_at before
update
    on
    public.admins for each row execute function set_updated_at();


-- public.apriori_results definition

-- Drop table

-- DROP TABLE public.apriori_results;

CREATE TABLE public.apriori_results (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	assessment_id int8 NOT NULL,
	user_id uuid NOT NULL,
	apriori_result int4 NOT NULL,
	counseling_status_id int4 NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT apriori_results_assessment_id_key UNIQUE (assessment_id),
	CONSTRAINT apriori_results_pkey PRIMARY KEY (id)
);
CREATE INDEX apriori_results_status_idx ON public.apriori_results USING btree (counseling_status_id);
CREATE INDEX apriori_results_user_created_idx ON public.apriori_results USING btree (user_id, created_at DESC);


-- public.assessment_reminders definition

-- Drop table

-- DROP TABLE public.assessment_reminders;

CREATE TABLE public.assessment_reminders (
	id uuid DEFAULT auth.uid() NOT NULL,
	user_id uuid GENERATED ALWAYS AS (id) STORED NULL,
	last_assessment_at timestamptz NULL,
	reminder_sent bool DEFAULT false NOT NULL,
	unanswered_reminder_sent bool DEFAULT false NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT assessment_reminders_pkey PRIMARY KEY (id),
	CONSTRAINT assessment_reminders_user_id_key UNIQUE (user_id)
);
CREATE INDEX assessment_reminders_last_sent_idx ON public.assessment_reminders USING btree (last_assessment_at, reminder_sent, unanswered_reminder_sent);

-- Table Triggers

create trigger set_assessment_reminders_updated_at before
update
    on
    public.assessment_reminders for each row execute function set_updated_at();


-- public.assessments definition

-- Drop table

-- DROP TABLE public.assessments;

CREATE TABLE public.assessments (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid NOT NULL,
	responses _int4 NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT assessments_pkey PRIMARY KEY (id),
	CONSTRAINT assessments_responses_length CHECK ((cardinality(responses) = 23))
);
CREATE INDEX assessments_user_created_idx ON public.assessments USING btree (user_id, created_at DESC);


-- public.personal_details definition

-- Drop table

-- DROP TABLE public.personal_details;

CREATE TABLE public.personal_details (
	user_id uuid DEFAULT auth.uid() NOT NULL,
	email text NOT NULL,
	first_name text NOT NULL,
	middle_name text NULL,
	last_name text NOT NULL,
	name_suffix text NULL,
	student_number text NOT NULL,
	birth_date date NOT NULL,
	program_id int4 NULL,
	"year" int2 NOT NULL,
	marital_status_id int4 NULL,
	is_working_student bool DEFAULT false NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT personal_details_email_key UNIQUE (email),
	CONSTRAINT personal_details_pkey PRIMARY KEY (user_id),
	CONSTRAINT personal_details_student_number_key UNIQUE (student_number),
	CONSTRAINT personal_details_year_check CHECK (((year >= 1) AND (year <= 5))),
	CONSTRAINT student_number_format CHECK ((student_number ~ '^[0-9]{4}-[0-9]{5}-[A-Z]{2}-[0-9]$'::text))
);

-- Table Triggers

create trigger set_personal_details_updated_at before
update
    on
    public.personal_details for each row execute function set_updated_at();


-- public.profiles definition

-- Drop table

-- DROP TABLE public.profiles;

CREATE TABLE public.profiles (
	id uuid DEFAULT auth.uid() NOT NULL,
	full_name text NULL,
	username text NULL,
	avatar_url text NULL,
	is_student bool DEFAULT true NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT profiles_pkey PRIMARY KEY (id),
	CONSTRAINT profiles_username_key UNIQUE (username)
);

-- Table Triggers

create trigger set_profiles_updated_at before
update
    on
    public.profiles for each row execute function set_updated_at();


-- public.apriori_results foreign keys

ALTER TABLE public.apriori_results ADD CONSTRAINT apriori_results_apriori_result_fkey FOREIGN KEY (apriori_result) REFERENCES public.assessment_scenarios(id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE public.apriori_results ADD CONSTRAINT apriori_results_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id) ON DELETE CASCADE;
ALTER TABLE public.apriori_results ADD CONSTRAINT apriori_results_counseling_status_id_fkey FOREIGN KEY (counseling_status_id) REFERENCES public.counseling_statuses(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE public.apriori_results ADD CONSTRAINT apriori_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;


-- public.assessment_reminders foreign keys

ALTER TABLE public.assessment_reminders ADD CONSTRAINT assessment_reminders_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id) ON DELETE CASCADE;


-- public.assessments foreign keys

ALTER TABLE public.assessments ADD CONSTRAINT assessments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;


-- public.personal_details foreign keys

ALTER TABLE public.personal_details ADD CONSTRAINT personal_details_marital_status_id_fkey FOREIGN KEY (marital_status_id) REFERENCES public.marital_statuses(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE public.personal_details ADD CONSTRAINT personal_details_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE public.personal_details ADD CONSTRAINT personal_details_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;


-- public.profiles foreign keys

ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


-- DROP FUNCTION public.count_apriori_results_by_scenario();

CREATE OR REPLACE FUNCTION public.count_apriori_results_by_scenario()
 RETURNS TABLE(scenario_name text, result_count bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select
    s.name as scenario_name,
    count(*)::bigint as result_count
  from public.apriori_results ar
  join public.assessment_scenarios s on s.id = ar.apriori_result
  group by s.id, s.name
  order by s.id;
$function$
;

-- DROP FUNCTION public.count_scenario_decrease();

CREATE OR REPLACE FUNCTION public.count_scenario_decrease()
 RETURNS TABLE(count bigint)
 LANGUAGE sql
 STABLE
AS $function$
  with ordered_results as (
    select
      user_id,
      apriori_result,
      lag(apriori_result) over (partition by user_id order by created_at) as previous_result
    from public.apriori_results
  )
  select count(*)::bigint
  from ordered_results
  where previous_result is not null
    and apriori_result < previous_result;
$function$
;

-- DROP FUNCTION public.count_scenario_increase();

CREATE OR REPLACE FUNCTION public.count_scenario_increase()
 RETURNS TABLE(count bigint)
 LANGUAGE sql
 STABLE
AS $function$
  with ordered_results as (
    select
      user_id,
      apriori_result,
      lag(apriori_result) over (partition by user_id order by created_at) as previous_result
    from public.apriori_results
  )
  select count(*)::bigint
  from ordered_results
  where previous_result is not null
    and apriori_result > previous_result;
$function$
;

-- DROP FUNCTION public.count_students();

CREATE OR REPLACE FUNCTION public.count_students()
 RETURNS TABLE(total bigint, answered_assessments_total bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select
    (select count(*)::bigint from public.personal_details) as total,
    (select count(distinct a.user_id)::bigint from public.assessments a) as answered_assessments_total;
$function$
;

-- DROP FUNCTION public.count_students_by_program();

CREATE OR REPLACE FUNCTION public.count_students_by_program()
 RETURNS TABLE(program_initial text, result_count bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select
    p.initial as program_initial,
    count(pd.user_id)::bigint as result_count
  from public.personal_details pd
  left join public.programs p on p.id = pd.program_id
  group by p.initial
  order by p.initial;
$function$
;

-- DROP FUNCTION public.count_users_with_specific_assessment_count(int4);

CREATE OR REPLACE FUNCTION public.count_users_with_specific_assessment_count(assessment_count integer)
 RETURNS TABLE(user_count bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select count(*)::bigint as user_count
  from (
    select a.user_id
    from public.assessments a
    group by a.user_id
    having count(*) = assessment_count
  ) counted_users;
$function$
;

-- DROP FUNCTION public.count_working_student();

CREATE OR REPLACE FUNCTION public.count_working_student()
 RETURNS TABLE(count bigint, total bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select
    (select count(*)::bigint from public.personal_details where is_working_student) as count,
    (select count(*)::bigint from public.personal_details) as total;
$function$
;

-- DROP FUNCTION public.filter_assessments_by_domains(jsonb, _int4);

CREATE OR REPLACE FUNCTION public.filter_assessments_by_domains(mappeddata jsonb, domain_ids integer[])
 RETURNS TABLE(response jsonb)
 LANGUAGE plpgsql
 STABLE
AS $function$
declare
  assessment_row jsonb;
  answers integer[];
  domain_row record;
  matched_domains jsonb;
begin
  for assessment_row in
    select value
    from jsonb_array_elements(mappeddata) as t(value)
  loop
    answers := array(
      select value::integer
      from jsonb_array_elements_text(coalesce(assessment_row -> 'responses', '[]'::jsonb)) with ordinality as x(value, ord)
      order by ord
    );

    matched_domains := '[]'::jsonb;

    for domain_row in
      select id, name, question_indexes
      from public.assessment_domains
      where id = any(domain_ids)
      order by id
    loop
      if exists (
        select 1
        from unnest(domain_row.question_indexes) as q(question_index)
        where coalesce(answers[q.question_index + 1], 0) > 0
      ) then
        matched_domains := matched_domains || jsonb_build_array(
          jsonb_build_object('domain_name', domain_row.name)
        );
      end if;
    end loop;

    response := matched_domains;
    return next;
  end loop;
end;
$function$
;

-- DROP FUNCTION public.get_answered_assessments_trend(text);

CREATE OR REPLACE FUNCTION public.get_answered_assessments_trend(scenario_name text)
 RETURNS TABLE(session_date timestamp with time zone, count bigint)
 LANGUAGE sql
 STABLE
AS $function$
  select
    date_trunc('day', ar.created_at) as session_date,
    count(*)::bigint as count
  from public.apriori_results ar
  join public.assessment_scenarios s on s.id = ar.apriori_result
  where s.name = scenario_name
  group by 1
  order by 1;
$function$
;

-- DROP FUNCTION public.get_answered_assessments_trend_by_student(uuid);

CREATE OR REPLACE FUNCTION public.get_answered_assessments_trend_by_student(user_id uuid)
 RETURNS TABLE(session_date timestamp with time zone, scenario_id integer)
 LANGUAGE sql
 STABLE
AS $function$
  select
    ar.created_at as session_date,
    ar.apriori_result as scenario_id
  from public.apriori_results ar
  where ar.user_id = user_id
  order by ar.created_at;
$function$
;

-- DROP FUNCTION public.get_assessments_table(text, text, text, text, text);

CREATE OR REPLACE FUNCTION public.get_assessments_table(search_query text, selected_scenario_name text, selected_status_name text, page_size text, page_number text)
 RETURNS TABLE(total_count bigint, id bigint, created_at timestamp with time zone, user_id uuid, first_name text, middle_name text, last_name text, name_suffix text, student_number text, result_scenario text, counseling_status text)
 LANGUAGE sql
 STABLE
AS $function$
  with base as (
    select
      count(*) over () as total_count,
      ar.id,
      a.created_at,
      ar.user_id,
      pd.first_name,
      pd.middle_name,
      pd.last_name,
      pd.name_suffix,
      pd.student_number,
      s.name as result_scenario,
      coalesce(cs.name, '') as counseling_status
    from public.apriori_results ar
    join public.assessments a on a.id = ar.assessment_id
    join public.personal_details pd on pd.user_id = ar.user_id
    join public.assessment_scenarios s on s.id = ar.apriori_result
    left join public.counseling_statuses cs on cs.id = ar.counseling_status_id
    where (
      search_query is null
      or search_query = ''
      or concat_ws(' ', pd.first_name, pd.middle_name, pd.last_name, pd.name_suffix, pd.student_number) ilike '%' || search_query || '%'
    )
    and (
      selected_scenario_name is null
      or selected_scenario_name = ''
      or s.name = selected_scenario_name
    )
    and (
      selected_status_name is null
      or selected_status_name = ''
      or coalesce(cs.name, '') = selected_status_name
    )
    order by a.created_at desc
    offset ((greatest(coalesce(nullif(page_number, '')::int, 1), 1) - 1) * greatest(coalesce(nullif(page_size, '')::int, 20), 1))
    limit greatest(coalesce(nullif(page_size, '')::int, 20), 1)
  )
  select * from base;
$function$
;

-- DROP FUNCTION public.get_users_with_multiple_assessments(text, text, text, text, text);

CREATE OR REPLACE FUNCTION public.get_users_with_multiple_assessments(result_count text, selected_program_initial text, search_query text, page_size text, page_number text)
 RETURNS TABLE(total_count bigint, user_id uuid, first_name text, middle_name text, last_name text, name_suffix text, student_number text, email text, birth_date date, program_initial text, program_name text, year smallint, marital_status text, is_working_student boolean)
 LANGUAGE sql
 STABLE
AS $function$
  with assessment_counts as (
    select
      a.user_id,
      count(*)::integer as assessment_count
    from public.assessments a
    group by a.user_id
  ),
  base as (
    select
      count(*) over () as total_count,
      pd.user_id,
      pd.first_name,
      pd.middle_name,
      pd.last_name,
      pd.name_suffix,
      pd.student_number,
      pd.email,
      pd.birth_date,
      p.initial as program_initial,
      p.name as program_name,
      pd.year,
      ms.status as marital_status,
      pd.is_working_student
    from public.personal_details pd
    left join public.programs p on p.id = pd.program_id
    left join public.marital_statuses ms on ms.id = pd.marital_status_id
    left join assessment_counts ac on ac.user_id = pd.user_id
    where (
      result_count is null
      or result_count = ''
      or coalesce(ac.assessment_count, 0) = nullif(result_count, '')::int
    )
    and (
      selected_program_initial is null
      or selected_program_initial = ''
      or p.initial = selected_program_initial
    )
    and (
      search_query is null
      or search_query = ''
      or concat_ws(' ', pd.first_name, pd.middle_name, pd.last_name, pd.name_suffix, pd.student_number) ilike '%' || search_query || '%'
    )
    order by pd.first_name, pd.last_name, pd.student_number
    offset ((greatest(coalesce(nullif(page_number, '')::int, 1), 1) - 1) * greatest(coalesce(nullif(page_size, '')::int, 20), 1))
    limit greatest(coalesce(nullif(page_size, '')::int, 20), 1)
  )
  select * from base;
$function$
;

-- DROP FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, full_name, is_student)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      new.email
    ),
    coalesce((new.raw_user_meta_data ->> 'is_student')::boolean, true)
  )
  on conflict (id) do nothing;

  return new;
end;
$function$
;

-- DROP FUNCTION public.is_admin_user();

CREATE OR REPLACE FUNCTION public.is_admin_user()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.admins a
    where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$function$
;

-- DROP FUNCTION public.rls_auto_enable();

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

-- DROP FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;