service: pupsrb-imhealth-admin-users

custom:
  config: ${file(../../environments/${opt:stage}.config.yml)}
  pythonRequirements:
    pythonBin: python
    slim: true

provider:
  name: aws
  runtime: python3.14
  architecture: x86_64
  region: ${self:custom.config.region}
  environment: ${self:custom.config.environment}
  layers: ${self:custom.config.layers}
  apiGateway: ${self:custom.config.apiGateway}
  iam:
    role: ${self:custom.config.lambdaRoleArn}

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.serverless/**"
    - "../../constants/**"
    - "../../utils/**"
    - "../../models/**"
    - "../../generic_dals/**"

functions:
  listAdminUsers:
    handler: admin_users.list_handler
    events:
      - http:
          path: /admin-users
          method: get
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers: [Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token]
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.authorizerId}

  createAdminUser:
    handler: admin_users.create_handler
    events:
      - http:
          path: /admin-users
          method: post
          cors:
            origin: ${self:custom.config.corsOrigin}
            headers: [Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token]
            allowCredentials: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.config.authorizerId}
