-- Purpose: administrator module permission matrix; required by utils/admin_permissions.py
-- and GET/PUT /admin/permissions. Apply manually before deploying the dependent API/web.
-- Prerequisites: public.admin_roles and public.admins match legacy/postgres_schema.sql;
-- confirm role names guidance_counselor, clinician, su_admin and at least one su_admin
-- administrator exists. No dependency on the earlier profile/settings patches.
-- Order: apply this additive patch after the existing baseline, before enabling new code.
-- Cognito identity uses verified email -> admins.email, not auth.users/profile IDs.
-- Existing Supabase auth helpers/policies/triggers are unchanged. These new tables have
-- no auth.* dependency. RLS below denies unprivileged direct access; the existing trusted
-- Lambda database role must have SELECT/INSERT/DELETE privileges and bypass RLS or own
-- these tables. Manually assess that role's grants; no credentials or IAM changes here.
-- First application seeds existing role access except guidance_counselor students read-only.
-- Reruns do not restore grants removed by an administrator: seed only newly registered
-- role/module pairs, tracked in admin_permission_seed_history. New roles fail closed until
-- explicitly configured. Small table locks expected; no existing student data changes.
BEGIN;
CREATE TABLE IF NOT EXISTS public.admin_modules (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 module_key text NOT NULL UNIQUE,
 module_name text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.admin_permission_types (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 permission_key text NOT NULL UNIQUE,
 permission_name text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.admin_role_permissions (
 role_id integer NOT NULL REFERENCES public.admin_roles(id) ON UPDATE CASCADE ON DELETE CASCADE,
 module_id integer NOT NULL REFERENCES public.admin_modules(id) ON DELETE CASCADE,
 permission_type_id integer NOT NULL REFERENCES public.admin_permission_types(id) ON DELETE CASCADE,
 PRIMARY KEY(role_id,module_id,permission_type_id)
);
CREATE TABLE IF NOT EXISTS public.admin_permission_seed_history (
 role_id integer NOT NULL REFERENCES public.admin_roles(id) ON DELETE CASCADE,
 module_id integer NOT NULL REFERENCES public.admin_modules(id) ON DELETE CASCADE,
 PRIMARY KEY(role_id,module_id)
);
ALTER TABLE public.admin_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_permission_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_permission_seed_history ENABLE ROW LEVEL SECURITY;
INSERT INTO public.admin_modules(module_key,module_name) VALUES
 ('dashboard','Dashboard'),('students','Students'),('assessments','Assessments'),
 ('reports','Reports'),('permissions','Role permissions') ON CONFLICT(module_key) DO NOTHING;
INSERT INTO public.admin_permission_types(permission_key,permission_name) VALUES
 ('read','Read'),('insert','Insert'),('update','Update'),('upload','Upload'),('download','Download')
 ON CONFLICT(permission_key) DO NOTHING;
WITH unseeded AS (
 SELECT r.id role_id,r.role_name,m.id module_id,m.module_key
 FROM public.admin_roles r CROSS JOIN public.admin_modules m
 WHERE r.role_name IN ('guidance_counselor','clinician','su_admin')
 AND NOT EXISTS(SELECT 1 FROM public.admin_permission_seed_history h WHERE h.role_id=r.id AND h.module_id=m.id)
), seeded AS (
 INSERT INTO public.admin_role_permissions(role_id,module_id,permission_type_id)
 SELECT u.role_id,u.module_id,t.id FROM unseeded u CROSS JOIN public.admin_permission_types t
 WHERE (u.module_key <> 'permissions' OR u.role_name='su_admin')
 AND (u.role_name <> 'guidance_counselor' OR u.module_key <> 'students' OR t.permission_key='read')
 ON CONFLICT DO NOTHING RETURNING role_id
)
INSERT INTO public.admin_permission_seed_history(role_id,module_id)
 SELECT role_id,module_id FROM unseeded ON CONFLICT DO NOTHING;
COMMIT;
-- Manual verification:
-- SELECT r.role_name,m.module_key,t.permission_key FROM public.admin_role_permissions g
-- JOIN public.admin_roles r ON r.id=g.role_id JOIN public.admin_modules m ON m.id=g.module_id
-- JOIN public.admin_permission_types t ON t.id=g.permission_type_id ORDER BY 1,2,3;
-- SELECT a.email FROM public.admins a JOIN public.admin_roles r ON r.id=a.role_id WHERE r.role_name='su_admin';
-- Verify guidance_counselor/students has ONLY read, other roles have no permissions module,
-- and the trusted application DB role can access these tables under its RLS/grant setup.
-- Rollback: first roll back dependent API/web code, export the grants for recovery, then
-- manually DROP TABLE public.admin_permission_seed_history, public.admin_role_permissions,
-- public.admin_permission_types, public.admin_modules; this loses permission settings only.
-- Report download is generated in the browser; download grants cannot revoke readable data.
